# Scientific Computing Libraries

Some essential scientific computing libraries in python are 
- [NumPy](https://numpy.org/): Numerical Python
- [SciPy](https://www.scipy.org/): Scientific Python
- [Matplotlib](https://matplotlib.org/): Plotting library
- [Seaborn](https://seaborn.pydata.org/): Statistical data visualization
- [Pandas](https://pandas.pydata.org/): Data analysis library
- [SymPy](https://www.sympy.org/en/index.html): Symbolic Python

You saw some of these utilized in the previous lecture, but in this lecture we'll introduce them a little more thoroughly.

# NumPy

Numpy is the fundamental package for scientific computing in Python. It provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [1]:
import numpy as np

## Numpy Essentials

To get used to some of the operators, we'll create some random arrays. Functions that do this in numpy include `np.random.rand` and `np.random.randn`. The first creates an array of random numbers between 0 and 1, while the second creates an array of random numbers from a standard normal distribution.

If you want to create an array of random integers, you can use `np.random.randint`. We'll use this for now to keep our math simpler.

In [2]:
np.random.randint(0, 10, size=5)

array([4, 2, 8, 1, 3])

In [3]:
a, b = np.random.randint(0, 10, size=2), np.random.randint(0, 10, size=1)
print(a, b)

[2 9] [9]


Let's do some basic operations

In [4]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 18]
[-7  0]
[18 81]
[0.22222222 1.        ]


In [5]:
a = [1,2,3]
b = [4,5,6]

In [24]:
a * 4

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [13]:
class trop(int):
    def __init__(self, x):
        super().__init__()
        self.x = x
    def __add__(self, y):
        return self.x * y
    # def __mul__(self, y):
    #     return max(self.x, y)
    def whatisthat(self):
        print("It's tropical")

In [15]:
a = trop(5)
b = trop(7)
c = int(6)
a * b

35

In [12]:
a.whatisthat()

It's tropical


In [7]:
old_int = int
int = 5
b = int(7)

TypeError: 'int' object is not callable

In [8]:
int = old_int

Note: it wasn't obvious, a priori, what to expect for division and multiplication, since these are vectors. However, we see that it does element-wise multiplication and division.

This isn't something we normally do in standard linear algebra, so let's so some of that with some 2x2 matrices.

In [34]:
a, b = np.random.randint(0, 10, size=(2,2)), np.random.randint(0, 10, size=(2,2))
print(a, "\n\n", b)

[[2 8]
 [1 6]] 

 [[6 1]
 [5 6]]


We can always see the shape of an array with the `shape` attribute.

In [33]:
a.shape

(2, 2, 10, 11)

Let's multiply

In [36]:
a @ b

array([[52, 50],
       [36, 37]])

In [37]:
np.matmul(a, b)

array([[52, 50],
       [36, 37]])

In [6]:
import numpy as np
print(dir(np.array))

['__call__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__self__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__text_signature__']


In [38]:
a @ np.linalg.inv(a)

array([[1., 0.],
       [0., 1.]])

## Numpy Linear Algebra

Ok, so we see the NumPy can do some linear algebra. What about some other operations?

Some of the most essential operations in `np.linalg` are:
- `np.linalg.inv`: Inverse of a matrix
- `np.linalg.det`: Determinant of a matrix
- `np.linalg.eig`: Eigenvalues and eigenvectors of a matrix
- `np.linalg.solve`: Solve a linear system of equations

We saw the first, let's see the rest

In this syntax `eigvecs[:,i]` means "all rows, column i". This is a common syntax in python, and is called "slicing". We'll see it again later.

In the context of this eigenvalue problem, if we're not careful we can do the wrong thing, because eigvecs is a matrix and we need to be careful whether the rows or columns are the eigenvectors. Let's see what happens if we do the wrong thing.

We see these clearly don't match.

So: just be careful. Simple tests can always help you sort things out

## Numpy Statistics

Some of the essential statistical tools in numpy are in `np.random` and `np.linalg`. We'll see some of these in action. Some of the most essential functions are:
- `np.random.rand`: Uniform random numbers in [0,1]
- `np.random.randn`: Standard normal random numbers
- `np.random.randint`: Random integers
- `np.random.choice`: Random choice from an array
- `np.random.shuffle`: Randomly shuffle an array
- `np.random.seed`: Set the random seed
- `np.mean`: Mean of an array
- `np.std`: Standard deviation of an array
- `np.var`: Variance of an array, which is the square of the standard deviation
- `np.cov`: Covariance matrix of an array, which is a matrix of all pairwise covariances. The diagional part of the covariance matrix is the variance of each variable.

Let's play with mean

That's the mean of the whole thing! What if we want the mean of each row?

And the mean of each column?

These shapes are the same, so be careful.

A lot of the other functions take an axis argument in a similar way.

Let's check out choice

## Numpy Code Lab

Let's do a simple example from quantum mechanics. The problem is perturbation theory,

$H = H_0 + \lambda H_1$

where $H$ is the Hamiltonian and $\lambda$ is a small parameter if perturbation theory is to work. If this is a good idea, it should work pretty well for *any* Hermitian $H_0$ and $H_1$. So we'll make them random Hermitian 3x3 matrices and see what happens.

We see it with our naked eye. Let's make it more quantitative by computing mean squared error of the exact energies relative to the perturbation theory energies, and plotting it

We see that when $\lambda$ is small, the perturbation theory energies are a good approximation to the exact energies, but when $\lambda$ is $\mathcal{O}(1)$, the MSE is large. This is a good sanity check.

# SciPy

SciPy is a collection of mathematical algorithms and convenience functions built on the Numpy extension of Python. Some of the main things it provides are functions for:
- Special functions (scipy.special)
- Integration (scipy.integrate)
- Optimization (scipy.optimize)


## SciPy Special Function

We'll play with SciPy special functions using the simply harmonic oscillator. The wavefunctions are given by Hermite polynomials times Gaussians, which are implemented in `scipy.special.hermite`. Let's plot the first few.

Let's check that this actually works by encoding the Hamiltonian in a differential operator and computing the energies. Recall that for $m=\hbar= \omega = 1$ the Hamiltonian is 

$H = -\frac{1}{2}\frac{d^2}{dx^2} + \frac{1}{2}x^2$

# SymPy

SymPy is a Python library for symbolic mathematics. It aims to become a full-featured computer algebra system (CAS) while keeping the code as simple as possible in order to be comprehensible and easily extensible. SymPy is written entirely in Python and does not require any external libraries.

Some of the essential things you can do with it are:
- Symbolic algebra
- Calculus
- Solving equations
- Discrete math
- Geometry

Symbolic Algebra Example

Let's try to solve some equations.

Let's do some discrete math

Remember that the Dihedral group D(4) is the group of symmetries of a square. What do you think these generators above mean? How can we check this idea?

We see that the generators rot and flip of the group D(4) satisfy the relations we expect:

$r^4=1, \qquad f^2=1$ 

This is a good sanity check.

Let's check convexity of the hull by putting an interior point inside and making sure it doesn't make it concave

Same thing! of course it is, because we just added an interior point, which doesn't change the convex hull.

# Summary

Clearly, we are only just scratching the surface of scientific computing in python. There are many more libraries and many more functions in these libraries. The best way to learn is to play around with them and see what you can do.

Methods of this "playing around" include:
- reading the docs to see what is out there
- doing something like ``import sympy.combinators as comb`` and then typing ``comb.<tab>`` to see what is available

But you can also use CoPilot to make suggestions that you can then see if they word. Here's an example, where all the bullets in the list below were auto generated, and the line above it is the prompt I gave.

Packages in python to do group theory include:
- [sympy.combinatorics](https://docs.sympy.org/latest/modules/combinatorics/index.html)
- [sympy.group](https://docs.sympy.org/latest/modules/group/index.html)
- [sympy.algebras](https://docs.sympy.org/latest/modules/algebras/index.html)
- [sympy.liealgebras](https://docs.sympy.org/latest/modules/liealgebras/index.html)

See, even I just learned ``sympy`` has Lie alebgra support! We use this all the time in high energy theory. Let's try it just for fun
